<?php
declare(strict_types=1);
$config=require __DIR__.'/config.php';
$appName=htmlspecialchars((string)$config['app_name'],ENT_QUOTES,'UTF-8');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0a0d14"><title><?= $appName ?></title><link rel="stylesheet" href="assets/css/style.css"><link rel="stylesheet" href="assets/css/attachments.css"><link rel="stylesheet" href="assets/css/artifacts.css"><link rel="stylesheet" href="assets/css/timing.css"><link rel="stylesheet" href="assets/css/settings.css"></head>
<body><div class="shell">
<aside class="sidebar" id="sidebar"><div class="brand"><span class="brand-mark">A</span><div><strong><?= $appName ?></strong><small>Ollama remoto</small></div></div><button class="new-chat" id="clear">＋ Nova conversa</button><nav class="side-nav"><button class="nav-item active">◉ Conversa</button><button class="nav-item" id="open-files">▤ Arquivos gerados</button><button class="nav-item" id="export-chat">⇩ Exportar conversa</button><button class="nav-item" id="open-models">⬡ Modelos</button><button class="nav-item" id="open-settings">⚙ Configurações</button></nav><div class="connection-card"><span id="status-dot" class="dot"></span><div><strong id="status">Verificando…</strong><small id="server-label">Servidor Ollama</small></div></div></aside>
<main class="workspace"><header class="topbar"><button id="menu" class="icon-btn mobile" aria-label="Abrir menu">☰</button><div class="model-control"><label for="model-select">Modelo</label><select id="model-select"><option value="" disabled selected>Conectando…</option></select></div><div class="top-actions"><button id="refresh" class="icon-btn" title="Atualizar conexão">↻</button><button id="settings-top" class="icon-btn" title="Configurações">⚙</button></div></header>
<section id="messages" class="messages" aria-live="polite"><div class="welcome" id="welcome"><div class="hero-mark">A</div><h1>Como posso ajudar?</h1><p>Converse com seu modelo local, consulte o banco ou envie uma imagem e documentos textuais.</p><div class="suggestions"><button data-prompt="Analise a estrutura do banco e explique as principais entidades.">Analisar o banco <span>→</span></button><button data-prompt="Quais são as cinco tabelas com mais registros?">Explorar dados <span>→</span></button><button data-prompt="Explique o código ou documento que vou anexar.">Analisar arquivo <span>→</span></button><button data-prompt="Qual é a data e a hora atual?">Testar o roteador <span>→</span></button></div></div></section>
<footer class="composer-wrap"><div id="attachments" class="attachments"></div><form id="chat-form" class="composer"><input id="files" type="file" multiple hidden accept="image/png,image/jpeg,image/webp,image/gif,text/*,.md,.csv,.json,.xml,.yaml,.yml,.php,.js,.ts,.css,.html,.sql,.py,.java,.c,.cpp,.h"><button type="button" id="attach" class="composer-icon attach-button" title="Enviar imagens, documentos de texto ou código" aria-label="Anexar arquivos"><span aria-hidden="true">📎</span><span class="attach-label">Anexar</span></button><textarea id="message" rows="1" maxlength="8000" placeholder="Envie uma mensagem…"></textarea><button id="send" type="submit" class="send" aria-label="Enviar">↑</button></form><p class="hint"><span id="composer-help">Enter envia · Shift+Enter quebra a linha · arquivos até 10 MB</span><span id="request-timer" class="request-timer" hidden></span></p></footer></main></div>
<dialog id="settings-dialog"><form class="dialog-card" id="settings-form"><header><div><h2>Conexão e geração</h2><p>As configurações salvas tornam-se o padrão deste servidor web.</p></div><button type="button" id="close-settings" class="close">×</button></header><label>URL do servidor<input id="server-url" type="url" placeholder="http://127.0.0.1:11434" required></label><label>Modelo padrão<input id="settings-model" placeholder="Será selecionado após conectar"></label><div class="settings-grid"><label>Temperatura<input id="settings-temperature" type="number" min="0" max="2" step="0.1" required></label><label>Contexto (tokens)<input id="settings-context" type="number" min="1024" max="262144" step="1024" required></label><label>Manter carregado<input id="settings-keepalive" placeholder="30m" pattern="0|[0-9]+[smh]" required></label></div><p class="field-help">Deixe o modelo vazio para selecionar automaticamente o primeiro modelo instalado no novo servidor. Contextos maiores consomem mais VRAM.</p><div id="settings-feedback" class="settings-feedback" hidden></div><div class="dialog-actions"><button type="button" id="cancel-settings" class="ghost">Fechar</button><button type="submit" class="primary">Testar e salvar</button></div></form></dialog>
<dialog id="models-dialog"><div class="dialog-card wide"><header><div><h2>Gerenciar modelos</h2><p>Instale, carregue ou libere modelos no servidor remoto.</p></div><button class="close" data-close="models-dialog">×</button></header><form id="pull-form" class="inline-form"><input id="pull-name" placeholder="Ex.: gemma3:4b" required><button class="primary">Instalar modelo</button></form><div id="model-operation" class="operation"></div><div id="model-list" class="model-list"></div></div></dialog>
<dialog id="files-dialog"><div class="dialog-card wide"><header><div><h2>Arquivos gerados</h2><p>Downloads desta sessão expiram automaticamente em 24 horas.</p></div><button class="close" data-close="files-dialog">×</button></header><div id="files-list" class="generated-list"></div></div></dialog>
<div id="toast" class="toast" role="status"></div><script src="assets/js/app.js" defer></script></body></html>
